# --- !Ups

ALTER TABLE UserApiKey CHANGE COLUMN label name VARCHAR(255) NOT NULL;
ALTER TABLE Page ADD COLUMN userApiKey BIGINT NULL AFTER viaApi;
ALTER TABLE Page ADD CONSTRAINT Page_UserApiKey_seq_fk FOREIGN KEY (userApiKey) REFERENCES UserApiKey (seq) ON DELETE SET NULL;

# --- !Downs

ALTER TABLE Page DROP FOREIGN KEY Page_UserApiKey_seq_fk;
ALTER TABLE Page DROP COLUMN userApiKey;
ALTER TABLE UserApiKey CHANGE COLUMN name label VARCHAR(255) NOT NULL;
