name: dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: ls

  build:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
